#pragma once

enum TEXTYPE { TEX_SINGLE, TEX_MULTI, TEX_END };

enum RENDERID { RENDER_BACKGROUND, RENDER_GAMEOBJECT, RENDER_BULLET, RENDER_EFFECT, RENDER_UI,RENDER_TARGETLINE, RENDER_END };

enum SCENEID { SC_START, SC_MAIN, SC_ZELDA, SC_FLASHMAN, SC_ZELDA_EDIT, SC_FORTRESS, SC_BRAWL_STARS, SC_MOMO, SC_END };

enum MOMOID { MOMO_PLAYER, MOMO_WEAPON, MOMO_END };

enum MOMO_WEAPONID { MOMOWEAPON_GUN, MOMOWEAPON_SWORD, MOMOWEAPON_END };

enum BRAWLID { BRAWL_BULLET ,   BRAWL_END };

enum ZELDA_OBJID { ZELDAOBJ_WALL, ZELDAOBJ_STONE, ZELDAOBJ_BUTTON, ZELDAOBJ_END };

enum FLASHMAN_PLAYERID { FLASHMAN_RED, FLASHMAN_BLUE, FLASHMAN_YELLOW, FLASHMAN_END };

enum MOMO_MONSTERID { MOMO_FOLLOW, MOMO_ROTATION, MOMO_MONSTEREND};

enum BULLET_ID { BULLET_BASIC, BULLET_DP, BULLET_END};

