#pragma once

enum RENDERID { RENDER_BACKGROUND, RENDER_GAMEOBJECT, RENDER_BULLET, RENDER_EFFECT, RENDER_UI, RENDER_END };

enum SCENEID { SC_START, SC_MAIN, SC_ZELDA, SC_FORTRESS, SC_BRAWL_STARS, SC_MOMO, SC_END };

enum MOMOID { MOMO_PLAYER, MOMO_END };